print("hello Mindi")
print('hello again mindi')
print('hello again mindi')
print('hello again mindi')
print('hello again mindi')
print('hello again mindi, and this is final helloooooo')
print('yeah so I swear, hello again mindi, and this is final helloooooo')